# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gerich/coding/SHAD/EM/practice_01

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gerich/coding/SHAD/EM/practice_01

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gerich/coding/SHAD/EM/practice_01/CMakeFiles /home/gerich/coding/SHAD/EM/practice_01/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gerich/coding/SHAD/EM/practice_01/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named em_test

# Build rule for target.
em_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 em_test
.PHONY : em_test

# fast build rule for target.
em_test/fast:
	$(MAKE) -f CMakeFiles/em_test.dir/build.make CMakeFiles/em_test.dir/build
.PHONY : em_test/fast

#=============================================================================
# Target rules for targets named parser

# Build rule for target.
parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parser
.PHONY : parser

# fast build rule for target.
parser/fast:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/build
.PHONY : parser/fast

#=============================================================================
# Target rules for targets named sorter

# Build rule for target.
sorter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sorter
.PHONY : sorter

# fast build rule for target.
sorter/fast:
	$(MAKE) -f CMakeFiles/sorter.dir/build.make CMakeFiles/sorter.dir/build
.PHONY : sorter/fast

em_test.o: em_test.cpp.o
.PHONY : em_test.o

# target to build an object file
em_test.cpp.o:
	$(MAKE) -f CMakeFiles/em_test.dir/build.make CMakeFiles/em_test.dir/em_test.cpp.o
.PHONY : em_test.cpp.o

em_test.i: em_test.cpp.i
.PHONY : em_test.i

# target to preprocess a source file
em_test.cpp.i:
	$(MAKE) -f CMakeFiles/em_test.dir/build.make CMakeFiles/em_test.dir/em_test.cpp.i
.PHONY : em_test.cpp.i

em_test.s: em_test.cpp.s
.PHONY : em_test.s

# target to generate assembly for a file
em_test.cpp.s:
	$(MAKE) -f CMakeFiles/em_test.dir/build.make CMakeFiles/em_test.dir/em_test.cpp.s
.PHONY : em_test.cpp.s

parser.o: parser.cpp.o
.PHONY : parser.o

# target to build an object file
parser.cpp.o:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/parser.cpp.o
.PHONY : parser.cpp.o

parser.i: parser.cpp.i
.PHONY : parser.i

# target to preprocess a source file
parser.cpp.i:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/parser.cpp.i
.PHONY : parser.cpp.i

parser.s: parser.cpp.s
.PHONY : parser.s

# target to generate assembly for a file
parser.cpp.s:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/parser.cpp.s
.PHONY : parser.cpp.s

sorter.o: sorter.cpp.o
.PHONY : sorter.o

# target to build an object file
sorter.cpp.o:
	$(MAKE) -f CMakeFiles/sorter.dir/build.make CMakeFiles/sorter.dir/sorter.cpp.o
.PHONY : sorter.cpp.o

sorter.i: sorter.cpp.i
.PHONY : sorter.i

# target to preprocess a source file
sorter.cpp.i:
	$(MAKE) -f CMakeFiles/sorter.dir/build.make CMakeFiles/sorter.dir/sorter.cpp.i
.PHONY : sorter.cpp.i

sorter.s: sorter.cpp.s
.PHONY : sorter.s

# target to generate assembly for a file
sorter.cpp.s:
	$(MAKE) -f CMakeFiles/sorter.dir/build.make CMakeFiles/sorter.dir/sorter.cpp.s
.PHONY : sorter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... em_test"
	@echo "... parser"
	@echo "... rebuild_cache"
	@echo "... sorter"
	@echo "... em_test.o"
	@echo "... em_test.i"
	@echo "... em_test.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... sorter.o"
	@echo "... sorter.i"
	@echo "... sorter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

